sonar.projectKey=appsealing_html5-player-drm-samples
sonar.organization=doverunner

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.min.js,**/media/**

sonar.javascript.file.suffixes=.js
sonar.html.file.suffixes=.html
